/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClassifiedsRouteImport } from './routes/classifieds'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassifiedsIdRouteImport } from './routes/classifieds.$id'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedMembersCardRouteImport } from './routes/_authenticated/members.card'
import { Route as AuthenticatedClassifiedsNewRouteImport } from './routes/_authenticated/classifieds.new'
import { Route as AuthenticatedClassifiedsMineRouteImport } from './routes/_authenticated/classifieds.mine'
import { Route as AuthenticatedAdminSponsorsRouteImport } from './routes/_authenticated/admin.sponsors'
import { Route as AuthenticatedAdminShopRouteImport } from './routes/_authenticated/admin.shop'
import { Route as AuthenticatedAdminNewsletterRouteImport } from './routes/_authenticated/admin.newsletter'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin.gallery'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminClassifiedsRouteImport } from './routes/_authenticated/admin.classifieds'
import { Route as ApiPublicNewsletterUnsubscribeRouteImport } from './routes/api/public/newsletter.unsubscribe'

const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifiedsRoute = ClassifiedsRouteImport.update({
  id: '/classifieds',
  path: '/classifieds',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifiedsIdRoute = ClassifiedsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClassifiedsRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersCardRoute =
  AuthenticatedMembersCardRouteImport.update({
    id: '/card',
    path: '/card',
    getParentRoute: () => AuthenticatedMembersRoute,
  } as any)
const AuthenticatedClassifiedsNewRoute =
  AuthenticatedClassifiedsNewRouteImport.update({
    id: '/classifieds/new',
    path: '/classifieds/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassifiedsMineRoute =
  AuthenticatedClassifiedsMineRouteImport.update({
    id: '/classifieds/mine',
    path: '/classifieds/mine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSponsorsRoute =
  AuthenticatedAdminSponsorsRouteImport.update({
    id: '/admin/sponsors',
    path: '/admin/sponsors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminShopRoute = AuthenticatedAdminShopRouteImport.update({
  id: '/admin/shop',
  path: '/admin/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminNewsletterRoute =
  AuthenticatedAdminNewsletterRouteImport.update({
    id: '/admin/newsletter',
    path: '/admin/newsletter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/admin/gallery',
    path: '/admin/gallery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/admin/events',
    path: '/admin/events',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClassifiedsRoute =
  AuthenticatedAdminClassifiedsRouteImport.update({
    id: '/admin/classifieds',
    path: '/admin/classifieds',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicNewsletterUnsubscribeRoute =
  ApiPublicNewsletterUnsubscribeRouteImport.update({
    id: '/api/public/newsletter/unsubscribe',
    path: '/api/public/newsletter/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/classifieds': typeof ClassifiedsRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/members': typeof AuthenticatedMembersRouteWithChildren
  '/classifieds/$id': typeof ClassifiedsIdRoute
  '/admin/classifieds': typeof AuthenticatedAdminClassifiedsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/shop': typeof AuthenticatedAdminShopRoute
  '/admin/sponsors': typeof AuthenticatedAdminSponsorsRoute
  '/classifieds/mine': typeof AuthenticatedClassifiedsMineRoute
  '/classifieds/new': typeof AuthenticatedClassifiedsNewRoute
  '/members/card': typeof AuthenticatedMembersCardRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/classifieds': typeof ClassifiedsRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/members': typeof AuthenticatedMembersRouteWithChildren
  '/classifieds/$id': typeof ClassifiedsIdRoute
  '/admin/classifieds': typeof AuthenticatedAdminClassifiedsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/shop': typeof AuthenticatedAdminShopRoute
  '/admin/sponsors': typeof AuthenticatedAdminSponsorsRoute
  '/classifieds/mine': typeof AuthenticatedClassifiedsMineRoute
  '/classifieds/new': typeof AuthenticatedClassifiedsNewRoute
  '/members/card': typeof AuthenticatedMembersCardRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/classifieds': typeof ClassifiedsRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRouteWithChildren
  '/classifieds/$id': typeof ClassifiedsIdRoute
  '/_authenticated/admin/classifieds': typeof AuthenticatedAdminClassifiedsRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/_authenticated/admin/shop': typeof AuthenticatedAdminShopRoute
  '/_authenticated/admin/sponsors': typeof AuthenticatedAdminSponsorsRoute
  '/_authenticated/classifieds/mine': typeof AuthenticatedClassifiedsMineRoute
  '/_authenticated/classifieds/new': typeof AuthenticatedClassifiedsNewRoute
  '/_authenticated/members/card': typeof AuthenticatedMembersCardRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/classifieds'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/join'
    | '/reset-password'
    | '/shop'
    | '/sitemap.xml'
    | '/sponsors'
    | '/members'
    | '/classifieds/$id'
    | '/admin/classifieds'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/newsletter'
    | '/admin/shop'
    | '/admin/sponsors'
    | '/classifieds/mine'
    | '/classifieds/new'
    | '/members/card'
    | '/api/public/newsletter/unsubscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/classifieds'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/join'
    | '/reset-password'
    | '/shop'
    | '/sitemap.xml'
    | '/sponsors'
    | '/members'
    | '/classifieds/$id'
    | '/admin/classifieds'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/newsletter'
    | '/admin/shop'
    | '/admin/sponsors'
    | '/classifieds/mine'
    | '/classifieds/new'
    | '/members/card'
    | '/api/public/newsletter/unsubscribe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/classifieds'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/join'
    | '/reset-password'
    | '/shop'
    | '/sitemap.xml'
    | '/sponsors'
    | '/_authenticated/members'
    | '/classifieds/$id'
    | '/_authenticated/admin/classifieds'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/newsletter'
    | '/_authenticated/admin/shop'
    | '/_authenticated/admin/sponsors'
    | '/_authenticated/classifieds/mine'
    | '/_authenticated/classifieds/new'
    | '/_authenticated/members/card'
    | '/api/public/newsletter/unsubscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ClassifiedsRoute: typeof ClassifiedsRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  JoinRoute: typeof JoinRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SponsorsRoute: typeof SponsorsRoute
  ApiPublicNewsletterUnsubscribeRoute: typeof ApiPublicNewsletterUnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifieds': {
      id: '/classifieds'
      path: '/classifieds'
      fullPath: '/classifieds'
      preLoaderRoute: typeof ClassifiedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifieds/$id': {
      id: '/classifieds/$id'
      path: '/$id'
      fullPath: '/classifieds/$id'
      preLoaderRoute: typeof ClassifiedsIdRouteImport
      parentRoute: typeof ClassifiedsRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/card': {
      id: '/_authenticated/members/card'
      path: '/card'
      fullPath: '/members/card'
      preLoaderRoute: typeof AuthenticatedMembersCardRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/_authenticated/classifieds/new': {
      id: '/_authenticated/classifieds/new'
      path: '/classifieds/new'
      fullPath: '/classifieds/new'
      preLoaderRoute: typeof AuthenticatedClassifiedsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classifieds/mine': {
      id: '/_authenticated/classifieds/mine'
      path: '/classifieds/mine'
      fullPath: '/classifieds/mine'
      preLoaderRoute: typeof AuthenticatedClassifiedsMineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sponsors': {
      id: '/_authenticated/admin/sponsors'
      path: '/admin/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AuthenticatedAdminSponsorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/shop': {
      id: '/_authenticated/admin/shop'
      path: '/admin/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AuthenticatedAdminShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/newsletter': {
      id: '/_authenticated/admin/newsletter'
      path: '/admin/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AuthenticatedAdminNewsletterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/classifieds': {
      id: '/_authenticated/admin/classifieds'
      path: '/admin/classifieds'
      fullPath: '/admin/classifieds'
      preLoaderRoute: typeof AuthenticatedAdminClassifiedsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/newsletter/unsubscribe': {
      id: '/api/public/newsletter/unsubscribe'
      path: '/api/public/newsletter/unsubscribe'
      fullPath: '/api/public/newsletter/unsubscribe'
      preLoaderRoute: typeof ApiPublicNewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMembersRouteChildren {
  AuthenticatedMembersCardRoute: typeof AuthenticatedMembersCardRoute
}

const AuthenticatedMembersRouteChildren: AuthenticatedMembersRouteChildren = {
  AuthenticatedMembersCardRoute: AuthenticatedMembersCardRoute,
}

const AuthenticatedMembersRouteWithChildren =
  AuthenticatedMembersRoute._addFileChildren(AuthenticatedMembersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRouteWithChildren
  AuthenticatedAdminClassifiedsRoute: typeof AuthenticatedAdminClassifiedsRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminNewsletterRoute: typeof AuthenticatedAdminNewsletterRoute
  AuthenticatedAdminShopRoute: typeof AuthenticatedAdminShopRoute
  AuthenticatedAdminSponsorsRoute: typeof AuthenticatedAdminSponsorsRoute
  AuthenticatedClassifiedsMineRoute: typeof AuthenticatedClassifiedsMineRoute
  AuthenticatedClassifiedsNewRoute: typeof AuthenticatedClassifiedsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMembersRoute: AuthenticatedMembersRouteWithChildren,
  AuthenticatedAdminClassifiedsRoute: AuthenticatedAdminClassifiedsRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
  AuthenticatedAdminNewsletterRoute: AuthenticatedAdminNewsletterRoute,
  AuthenticatedAdminShopRoute: AuthenticatedAdminShopRoute,
  AuthenticatedAdminSponsorsRoute: AuthenticatedAdminSponsorsRoute,
  AuthenticatedClassifiedsMineRoute: AuthenticatedClassifiedsMineRoute,
  AuthenticatedClassifiedsNewRoute: AuthenticatedClassifiedsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClassifiedsRouteChildren {
  ClassifiedsIdRoute: typeof ClassifiedsIdRoute
}

const ClassifiedsRouteChildren: ClassifiedsRouteChildren = {
  ClassifiedsIdRoute: ClassifiedsIdRoute,
}

const ClassifiedsRouteWithChildren = ClassifiedsRoute._addFileChildren(
  ClassifiedsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ClassifiedsRoute: ClassifiedsRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  JoinRoute: JoinRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SponsorsRoute: SponsorsRoute,
  ApiPublicNewsletterUnsubscribeRoute: ApiPublicNewsletterUnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
