/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClassifiedsRouteImport } from './routes/classifieds'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as ClassifiedsIndexRouteImport } from './routes/classifieds.index'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as ClassifiedsIdRouteImport } from './routes/classifieds.$id'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/_authenticated/members.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicEventRsvpRouteImport } from './routes/api/public/event-rsvp'
import { Route as ApiPublicEventImageRouteImport } from './routes/api/public/event-image'
import { Route as AuthenticatedMembersSponsorRouteImport } from './routes/_authenticated/members.sponsor'
import { Route as AuthenticatedMembersNotificationsRouteImport } from './routes/_authenticated/members.notifications'
import { Route as AuthenticatedMembersDirectoryRouteImport } from './routes/_authenticated/members.directory'
import { Route as AuthenticatedMembersCardRouteImport } from './routes/_authenticated/members.card'
import { Route as AuthenticatedMembersNumberRouteImport } from './routes/_authenticated/members.$number'
import { Route as AuthenticatedClassifiedsNewRouteImport } from './routes/_authenticated/classifieds.new'
import { Route as AuthenticatedClassifiedsMineRouteImport } from './routes/_authenticated/classifieds.mine'
import { Route as AuthenticatedAdminSponsorsRouteImport } from './routes/_authenticated/admin/sponsors'
import { Route as AuthenticatedAdminShopRouteImport } from './routes/_authenticated/admin/shop'
import { Route as AuthenticatedAdminNewsletterRouteImport } from './routes/_authenticated/admin/newsletter'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin/members'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin/gallery'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin/events'
import { Route as AuthenticatedAdminConcoursRouteImport } from './routes/_authenticated/admin/concours'
import { Route as AuthenticatedAdminClassifiedsRouteImport } from './routes/_authenticated/admin/classifieds'
import { Route as ApiPublicNewsletterUnsubscribeRouteImport } from './routes/api/public/newsletter.unsubscribe'

const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifiedsRoute = ClassifiedsRouteImport.update({
  id: '/classifieds',
  path: '/classifieds',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const ClassifiedsIndexRoute = ClassifiedsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClassifiedsRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const ClassifiedsIdRoute = ClassifiedsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClassifiedsRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMembersRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicEventRsvpRoute = ApiPublicEventRsvpRouteImport.update({
  id: '/api/public/event-rsvp',
  path: '/api/public/event-rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventImageRoute = ApiPublicEventImageRouteImport.update({
  id: '/api/public/event-image',
  path: '/api/public/event-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMembersSponsorRoute =
  AuthenticatedMembersSponsorRouteImport.update({
    id: '/sponsor',
    path: '/sponsor',
    getParentRoute: () => AuthenticatedMembersRoute,
  } as any)
const AuthenticatedMembersNotificationsRoute =
  AuthenticatedMembersNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedMembersRoute,
  } as any)
const AuthenticatedMembersDirectoryRoute =
  AuthenticatedMembersDirectoryRouteImport.update({
    id: '/directory',
    path: '/directory',
    getParentRoute: () => AuthenticatedMembersRoute,
  } as any)
const AuthenticatedMembersCardRoute =
  AuthenticatedMembersCardRouteImport.update({
    id: '/card',
    path: '/card',
    getParentRoute: () => AuthenticatedMembersRoute,
  } as any)
const AuthenticatedMembersNumberRoute =
  AuthenticatedMembersNumberRouteImport.update({
    id: '/$number',
    path: '/$number',
    getParentRoute: () => AuthenticatedMembersRoute,
  } as any)
const AuthenticatedClassifiedsNewRoute =
  AuthenticatedClassifiedsNewRouteImport.update({
    id: '/classifieds/new',
    path: '/classifieds/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassifiedsMineRoute =
  AuthenticatedClassifiedsMineRouteImport.update({
    id: '/classifieds/mine',
    path: '/classifieds/mine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSponsorsRoute =
  AuthenticatedAdminSponsorsRouteImport.update({
    id: '/sponsors',
    path: '/sponsors',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminShopRoute = AuthenticatedAdminShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminNewsletterRoute =
  AuthenticatedAdminNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConcoursRoute =
  AuthenticatedAdminConcoursRouteImport.update({
    id: '/concours',
    path: '/concours',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClassifiedsRoute =
  AuthenticatedAdminClassifiedsRouteImport.update({
    id: '/classifieds',
    path: '/classifieds',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicNewsletterUnsubscribeRoute =
  ApiPublicNewsletterUnsubscribeRouteImport.update({
    id: '/api/public/newsletter/unsubscribe',
    path: '/api/public/newsletter/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/classifieds': typeof ClassifiedsRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/members': typeof AuthenticatedMembersRouteWithChildren
  '/classifieds/$id': typeof ClassifiedsIdRoute
  '/events/$id': typeof EventsIdRoute
  '/classifieds/': typeof ClassifiedsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/admin/classifieds': typeof AuthenticatedAdminClassifiedsRoute
  '/admin/concours': typeof AuthenticatedAdminConcoursRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/shop': typeof AuthenticatedAdminShopRoute
  '/admin/sponsors': typeof AuthenticatedAdminSponsorsRoute
  '/classifieds/mine': typeof AuthenticatedClassifiedsMineRoute
  '/classifieds/new': typeof AuthenticatedClassifiedsNewRoute
  '/members/$number': typeof AuthenticatedMembersNumberRoute
  '/members/card': typeof AuthenticatedMembersCardRoute
  '/members/directory': typeof AuthenticatedMembersDirectoryRoute
  '/members/notifications': typeof AuthenticatedMembersNotificationsRoute
  '/members/sponsor': typeof AuthenticatedMembersSponsorRoute
  '/api/public/event-image': typeof ApiPublicEventImageRoute
  '/api/public/event-rsvp': typeof ApiPublicEventRsvpRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/members/': typeof AuthenticatedMembersIndexRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/classifieds/$id': typeof ClassifiedsIdRoute
  '/events/$id': typeof EventsIdRoute
  '/classifieds': typeof ClassifiedsIndexRoute
  '/events': typeof EventsIndexRoute
  '/admin/classifieds': typeof AuthenticatedAdminClassifiedsRoute
  '/admin/concours': typeof AuthenticatedAdminConcoursRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/shop': typeof AuthenticatedAdminShopRoute
  '/admin/sponsors': typeof AuthenticatedAdminSponsorsRoute
  '/classifieds/mine': typeof AuthenticatedClassifiedsMineRoute
  '/classifieds/new': typeof AuthenticatedClassifiedsNewRoute
  '/members/$number': typeof AuthenticatedMembersNumberRoute
  '/members/card': typeof AuthenticatedMembersCardRoute
  '/members/directory': typeof AuthenticatedMembersDirectoryRoute
  '/members/notifications': typeof AuthenticatedMembersNotificationsRoute
  '/members/sponsor': typeof AuthenticatedMembersSponsorRoute
  '/api/public/event-image': typeof ApiPublicEventImageRoute
  '/api/public/event-rsvp': typeof ApiPublicEventRsvpRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/members': typeof AuthenticatedMembersIndexRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/classifieds': typeof ClassifiedsRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/members': typeof AuthenticatedMembersRouteWithChildren
  '/classifieds/$id': typeof ClassifiedsIdRoute
  '/events/$id': typeof EventsIdRoute
  '/classifieds/': typeof ClassifiedsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/_authenticated/admin/classifieds': typeof AuthenticatedAdminClassifiedsRoute
  '/_authenticated/admin/concours': typeof AuthenticatedAdminConcoursRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/_authenticated/admin/shop': typeof AuthenticatedAdminShopRoute
  '/_authenticated/admin/sponsors': typeof AuthenticatedAdminSponsorsRoute
  '/_authenticated/classifieds/mine': typeof AuthenticatedClassifiedsMineRoute
  '/_authenticated/classifieds/new': typeof AuthenticatedClassifiedsNewRoute
  '/_authenticated/members/$number': typeof AuthenticatedMembersNumberRoute
  '/_authenticated/members/card': typeof AuthenticatedMembersCardRoute
  '/_authenticated/members/directory': typeof AuthenticatedMembersDirectoryRoute
  '/_authenticated/members/notifications': typeof AuthenticatedMembersNotificationsRoute
  '/_authenticated/members/sponsor': typeof AuthenticatedMembersSponsorRoute
  '/api/public/event-image': typeof ApiPublicEventImageRoute
  '/api/public/event-rsvp': typeof ApiPublicEventRsvpRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/members/': typeof AuthenticatedMembersIndexRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/classifieds'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/join'
    | '/reset-password'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/sponsors'
    | '/admin'
    | '/members'
    | '/classifieds/$id'
    | '/events/$id'
    | '/classifieds/'
    | '/events/'
    | '/admin/classifieds'
    | '/admin/concours'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/members'
    | '/admin/newsletter'
    | '/admin/shop'
    | '/admin/sponsors'
    | '/classifieds/mine'
    | '/classifieds/new'
    | '/members/$number'
    | '/members/card'
    | '/members/directory'
    | '/members/notifications'
    | '/members/sponsor'
    | '/api/public/event-image'
    | '/api/public/event-rsvp'
    | '/admin/'
    | '/members/'
    | '/api/public/newsletter/unsubscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/join'
    | '/reset-password'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/sponsors'
    | '/classifieds/$id'
    | '/events/$id'
    | '/classifieds'
    | '/events'
    | '/admin/classifieds'
    | '/admin/concours'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/members'
    | '/admin/newsletter'
    | '/admin/shop'
    | '/admin/sponsors'
    | '/classifieds/mine'
    | '/classifieds/new'
    | '/members/$number'
    | '/members/card'
    | '/members/directory'
    | '/members/notifications'
    | '/members/sponsor'
    | '/api/public/event-image'
    | '/api/public/event-rsvp'
    | '/admin'
    | '/members'
    | '/api/public/newsletter/unsubscribe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/classifieds'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/join'
    | '/reset-password'
    | '/robots.txt'
    | '/shop'
    | '/sitemap.xml'
    | '/sponsors'
    | '/_authenticated/admin'
    | '/_authenticated/members'
    | '/classifieds/$id'
    | '/events/$id'
    | '/classifieds/'
    | '/events/'
    | '/_authenticated/admin/classifieds'
    | '/_authenticated/admin/concours'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/newsletter'
    | '/_authenticated/admin/shop'
    | '/_authenticated/admin/sponsors'
    | '/_authenticated/classifieds/mine'
    | '/_authenticated/classifieds/new'
    | '/_authenticated/members/$number'
    | '/_authenticated/members/card'
    | '/_authenticated/members/directory'
    | '/_authenticated/members/notifications'
    | '/_authenticated/members/sponsor'
    | '/api/public/event-image'
    | '/api/public/event-rsvp'
    | '/_authenticated/admin/'
    | '/_authenticated/members/'
    | '/api/public/newsletter/unsubscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ClassifiedsRoute: typeof ClassifiedsRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  JoinRoute: typeof JoinRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SponsorsRoute: typeof SponsorsRoute
  ApiPublicEventImageRoute: typeof ApiPublicEventImageRoute
  ApiPublicEventRsvpRoute: typeof ApiPublicEventRsvpRoute
  ApiPublicNewsletterUnsubscribeRoute: typeof ApiPublicNewsletterUnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifieds': {
      id: '/classifieds'
      path: '/classifieds'
      fullPath: '/classifieds'
      preLoaderRoute: typeof ClassifiedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/classifieds/': {
      id: '/classifieds/'
      path: '/'
      fullPath: '/classifieds/'
      preLoaderRoute: typeof ClassifiedsIndexRouteImport
      parentRoute: typeof ClassifiedsRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/classifieds/$id': {
      id: '/classifieds/$id'
      path: '/$id'
      fullPath: '/classifieds/$id'
      preLoaderRoute: typeof ClassifiedsIdRouteImport
      parentRoute: typeof ClassifiedsRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members/': {
      id: '/_authenticated/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/event-rsvp': {
      id: '/api/public/event-rsvp'
      path: '/api/public/event-rsvp'
      fullPath: '/api/public/event-rsvp'
      preLoaderRoute: typeof ApiPublicEventRsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/event-image': {
      id: '/api/public/event-image'
      path: '/api/public/event-image'
      fullPath: '/api/public/event-image'
      preLoaderRoute: typeof ApiPublicEventImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/members/sponsor': {
      id: '/_authenticated/members/sponsor'
      path: '/sponsor'
      fullPath: '/members/sponsor'
      preLoaderRoute: typeof AuthenticatedMembersSponsorRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/_authenticated/members/notifications': {
      id: '/_authenticated/members/notifications'
      path: '/notifications'
      fullPath: '/members/notifications'
      preLoaderRoute: typeof AuthenticatedMembersNotificationsRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/_authenticated/members/directory': {
      id: '/_authenticated/members/directory'
      path: '/directory'
      fullPath: '/members/directory'
      preLoaderRoute: typeof AuthenticatedMembersDirectoryRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/_authenticated/members/card': {
      id: '/_authenticated/members/card'
      path: '/card'
      fullPath: '/members/card'
      preLoaderRoute: typeof AuthenticatedMembersCardRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/_authenticated/members/$number': {
      id: '/_authenticated/members/$number'
      path: '/$number'
      fullPath: '/members/$number'
      preLoaderRoute: typeof AuthenticatedMembersNumberRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/_authenticated/classifieds/new': {
      id: '/_authenticated/classifieds/new'
      path: '/classifieds/new'
      fullPath: '/classifieds/new'
      preLoaderRoute: typeof AuthenticatedClassifiedsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classifieds/mine': {
      id: '/_authenticated/classifieds/mine'
      path: '/classifieds/mine'
      fullPath: '/classifieds/mine'
      preLoaderRoute: typeof AuthenticatedClassifiedsMineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/sponsors': {
      id: '/_authenticated/admin/sponsors'
      path: '/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AuthenticatedAdminSponsorsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/shop': {
      id: '/_authenticated/admin/shop'
      path: '/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AuthenticatedAdminShopRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/newsletter': {
      id: '/_authenticated/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AuthenticatedAdminNewsletterRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/concours': {
      id: '/_authenticated/admin/concours'
      path: '/concours'
      fullPath: '/admin/concours'
      preLoaderRoute: typeof AuthenticatedAdminConcoursRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/classifieds': {
      id: '/_authenticated/admin/classifieds'
      path: '/classifieds'
      fullPath: '/admin/classifieds'
      preLoaderRoute: typeof AuthenticatedAdminClassifiedsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/newsletter/unsubscribe': {
      id: '/api/public/newsletter/unsubscribe'
      path: '/api/public/newsletter/unsubscribe'
      fullPath: '/api/public/newsletter/unsubscribe'
      preLoaderRoute: typeof ApiPublicNewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminClassifiedsRoute: typeof AuthenticatedAdminClassifiedsRoute
  AuthenticatedAdminConcoursRoute: typeof AuthenticatedAdminConcoursRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminNewsletterRoute: typeof AuthenticatedAdminNewsletterRoute
  AuthenticatedAdminShopRoute: typeof AuthenticatedAdminShopRoute
  AuthenticatedAdminSponsorsRoute: typeof AuthenticatedAdminSponsorsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminClassifiedsRoute: AuthenticatedAdminClassifiedsRoute,
    AuthenticatedAdminConcoursRoute: AuthenticatedAdminConcoursRoute,
    AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
    AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
    AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
    AuthenticatedAdminNewsletterRoute: AuthenticatedAdminNewsletterRoute,
    AuthenticatedAdminShopRoute: AuthenticatedAdminShopRoute,
    AuthenticatedAdminSponsorsRoute: AuthenticatedAdminSponsorsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedMembersRouteChildren {
  AuthenticatedMembersNumberRoute: typeof AuthenticatedMembersNumberRoute
  AuthenticatedMembersCardRoute: typeof AuthenticatedMembersCardRoute
  AuthenticatedMembersDirectoryRoute: typeof AuthenticatedMembersDirectoryRoute
  AuthenticatedMembersNotificationsRoute: typeof AuthenticatedMembersNotificationsRoute
  AuthenticatedMembersSponsorRoute: typeof AuthenticatedMembersSponsorRoute
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
}

const AuthenticatedMembersRouteChildren: AuthenticatedMembersRouteChildren = {
  AuthenticatedMembersNumberRoute: AuthenticatedMembersNumberRoute,
  AuthenticatedMembersCardRoute: AuthenticatedMembersCardRoute,
  AuthenticatedMembersDirectoryRoute: AuthenticatedMembersDirectoryRoute,
  AuthenticatedMembersNotificationsRoute:
    AuthenticatedMembersNotificationsRoute,
  AuthenticatedMembersSponsorRoute: AuthenticatedMembersSponsorRoute,
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
}

const AuthenticatedMembersRouteWithChildren =
  AuthenticatedMembersRoute._addFileChildren(AuthenticatedMembersRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRouteWithChildren
  AuthenticatedClassifiedsMineRoute: typeof AuthenticatedClassifiedsMineRoute
  AuthenticatedClassifiedsNewRoute: typeof AuthenticatedClassifiedsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedMembersRoute: AuthenticatedMembersRouteWithChildren,
  AuthenticatedClassifiedsMineRoute: AuthenticatedClassifiedsMineRoute,
  AuthenticatedClassifiedsNewRoute: AuthenticatedClassifiedsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClassifiedsRouteChildren {
  ClassifiedsIdRoute: typeof ClassifiedsIdRoute
  ClassifiedsIndexRoute: typeof ClassifiedsIndexRoute
}

const ClassifiedsRouteChildren: ClassifiedsRouteChildren = {
  ClassifiedsIdRoute: ClassifiedsIdRoute,
  ClassifiedsIndexRoute: ClassifiedsIndexRoute,
}

const ClassifiedsRouteWithChildren = ClassifiedsRoute._addFileChildren(
  ClassifiedsRouteChildren,
)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ClassifiedsRoute: ClassifiedsRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  GalleryRoute: GalleryRoute,
  JoinRoute: JoinRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SponsorsRoute: SponsorsRoute,
  ApiPublicEventImageRoute: ApiPublicEventImageRoute,
  ApiPublicEventRsvpRoute: ApiPublicEventRsvpRoute,
  ApiPublicNewsletterUnsubscribeRoute: ApiPublicNewsletterUnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
